import './globals.css'
import { Inter } from 'next/font/google'
import Header from "./components/Header";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'マルチモーダル作業支援システム（仮）',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body suppressHydrationWarning={true} className={inter.className}>
        <main>{children}</main>
      </body> 
    </html>
  )
};
